name: auto-merge

on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Clone repo'
        uses: actions/checkout@v2
      - name: 'Automerge dependency test-passing updates from Dependabot'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          # this seems kinda dumb but as of this comment seems to be the best approach:
          # https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60#issuecomment-846397027
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_PAT }}
