name: PR Tests
on:
  pull_request_target:
    branches:
      - main
    paths:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: test
        run: npm ci && npm run test
